export const FETCH_GIFS_BEGIN = "FETCH_GIFS_BEGIN";
export const FETCH_GIFS_SUCCESS = "FETCH_GIFS_SUCCESS";
export const FETCH_GIFS_FAILURE = "FETCH_GIFS_FAILURE";
export const INPUT_SEARCH = "INPUT_SEARCH";